# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-22 03:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u57ce\u5e02')),
                ('des', models.CharField(max_length=200, verbose_name='\u57ce\u5e02\u63cf\u8ff0')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u57ce\u5e02',
                'verbose_name_plural': '\u57ce\u5e02',
            },
        ),
        migrations.CreateModel(
            name='pet_boss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u8001\u677f\u540d\u5b57')),
                ('work_year', models.IntegerField(default=0, verbose_name='\u5f00\u5e97\u5e74\u9f84')),
                ('click_nums', models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u6570')),
                ('favorite_nums', models.IntegerField(default=0, verbose_name='\u6536\u85cf\u6570')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u5e97\u94faboss\u4fe1\u606f',
                'verbose_name_plural': '\u5e97\u94faboss\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='pet_organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u5e97\u540d')),
                ('des', models.TextField(verbose_name='\u5e97\u94fa\u63cf\u8ff0')),
                ('click_nums', models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u6570')),
                ('favorite_nums', models.IntegerField(default=0, verbose_name='\u6536\u85cf\u6570')),
                ('org_image', models.ImageField(upload_to='org/%Y/%m/%d', verbose_name='\u5ba0\u7269\u5c01\u9762\u56fe\u7247')),
                ('address', models.CharField(max_length=100, verbose_name='\u5b9e\u4f53\u5e97\u5730\u5740')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.City', verbose_name='\u5e97\u94fa\u57ce\u5e02')),
            ],
            options={
                'verbose_name': '\u5e97\u94fa',
                'verbose_name_plural': '\u5e97\u94fa',
            },
        ),
        migrations.AddField(
            model_name='pet_boss',
            name='work_org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.pet_organization', verbose_name='boss\u5e97\u94fa'),
        ),
    ]
