# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-26 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet_organization',
            name='catgory',
            field=models.CharField(choices=[('cwgs', '\u5ba0\u7269\u516c\u53f8'), ('zz', '\u7ec4\u7ec7'), ('gr', '\u4e2a\u4eba')], default='zz', max_length=20, verbose_name='\u5e97\u94fa\u7c7b\u522b'),
        ),
        migrations.AlterField(
            model_name='pet_organization',
            name='org_image',
            field=models.ImageField(upload_to='org_logo/%Y/%m', verbose_name='\u5ba0\u7269\u5e97\u94falogo'),
        ),
    ]
