# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-27 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20170626_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet_boss',
            name='boss_image',
            field=models.ImageField(blank=True, null=True, upload_to='boss_image/%Y/%m', verbose_name='\u5e97\u94fa\u8001\u677f\u5934\u50cf'),
        ),
    ]
