# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-22 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20170622_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userask',
            name='course_name',
        ),
        migrations.AddField(
            model_name='userask',
            name='pet_name',
            field=models.CharField(default='', max_length=50, verbose_name='\u5ba0\u7269\u540d\u79f0'),
        ),
    ]
