# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-22 03:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u5ba0\u7269\u540d\u79f0')),
                ('des', models.CharField(max_length=300, verbose_name='\u5ba0\u7269\u63cf\u8ff0')),
                ('detail', models.TextField(verbose_name='\u5ba0\u7269\u8be6\u60c5')),
                ('price', models.IntegerField(default=100, verbose_name='\u5ba0\u7269\u4ef7\u683c')),
                ('buy_people_num', models.IntegerField(default=100, verbose_name='\u8d2d\u4e70\u4eba\u6570')),
                ('age', models.FloatField(default=1.5, verbose_name='\u5ba0\u7269\u5e74\u9f84')),
                ('pet_type', models.CharField(max_length=50, verbose_name='\u5ba0\u7269\u7c7b\u522b')),
                ('pet_image', models.ImageField(upload_to='pets/%Y/%m/%d', verbose_name='\u5ba0\u7269\u5c01\u9762\u56fe\u7247')),
                ('click_nums', models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u6570')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u5ba0\u7269\u4fe1\u606f',
                'verbose_name_plural': '\u5ba0\u7269\u4fe1\u606f',
            },
        ),
    ]
