# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-27 01:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20170626_2120'),
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petinformation',
            name='pet_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.pet_organization', verbose_name='\u5ba0\u7269\u5e97\u94fa'),
        ),
    ]
