# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-27 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_petinformation_pet_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petinformation',
            name='pet_image',
            field=models.ImageField(upload_to='pets/%Y/%m', verbose_name='\u5ba0\u7269\u5c01\u9762\u56fe\u7247'),
        ),
    ]
